// <auto-generated />
using System;
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(FinalContext))]
    [Migration("20201202030311_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.ForumModel", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("F_scoreQuizID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("F_userUserID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostID");

                    b.HasIndex("F_scoreQuizID");

                    b.HasIndex("F_userUserID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("FinalProject.Models.QuizModel", b =>
                {
                    b.Property<string>("QuizID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Q_userUserID")
                        .HasColumnType("int");

                    b.Property<string>("Score")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizID");

                    b.HasIndex("Q_userUserID");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("FinalProject.Models.UserModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinalProject.Models.ForumModel", b =>
                {
                    b.HasOne("FinalProject.Models.QuizModel", "F_score")
                        .WithMany()
                        .HasForeignKey("F_scoreQuizID");

                    b.HasOne("FinalProject.Models.UserModel", "F_user")
                        .WithMany()
                        .HasForeignKey("F_userUserID");
                });

            modelBuilder.Entity("FinalProject.Models.QuizModel", b =>
                {
                    b.HasOne("FinalProject.Models.UserModel", "Q_user")
                        .WithMany()
                        .HasForeignKey("Q_userUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
